### PR TITLE
IA-652: Initial commit Deskmanager quickstart application

### PR DESCRIPTION
**Pull request by hkristof**
This is a copy of the Deskmanager example project, a bit cleaned up and names changed.

My vote: +1 (binding)

### CODE REVIEW

**Comment by janvenstermans** [comment]
travis build fails: maybe because of "empty" master branch.

Branch for this issue builds: http://ci.geomajas.org/jenkins/job/Geomajas%20Deskmanager%20quickstart%20application/
Cargo plugin deployed example at http://dev.geomajas.org/geomajas-deskmanager-quickstart-application-1.0.0-SNAPSHOT/manager/index.html

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by olivermay** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Vote count:
Kristof Heirwegh:  +1 (binding)
Oliver May: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
